import { Beat, DEFAULT_CAMERA } from './presentation.model';
import { SNIPPETS } from './snippets';

const cam = (partial: Partial<Beat['camera']> = {}): Beat['camera'] => ({
  ...DEFAULT_CAMERA,
  ...partial,
});

export const BEATS: Beat[] = [
  {
    id: 'a1-open',
    act: 1,
    label: 'Opening',
    headline: 'We need a production backend.',
    body: 'CineTrack is a movie-tracking product. The API must be fast, secure, modular, and documented from day one.',
    points: [
      { title: 'Product', body: 'Watchlists, favorites, ratings, journal, stats, recommendations, TMDb.' },
      { title: 'Constraint', body: 'One Node process — structured to grow.' },
      { title: 'Choice', body: 'Fastify 5 + MongoDB + Zod + plugins.' },
    ],
    stage: 'intro',
    camera: cam({ scale: 1.05 }),
    corePower: 0,
    sound: 'type',
  },
  {
    id: 'a1-goals',
    act: 1,
    label: 'Goals',
    headline: 'Six non‑negotiables.',
    body: 'Every architectural decision in CineTrack traces back to these.',
    points: [
      { title: 'Fast', body: 'Schema-compiled validation.' },
      { title: 'Secure', body: 'Helmet, CORS, JWT cookies, bcrypt, rate limits.' },
      { title: 'Modular', body: 'Feature plugins under /api/v1.' },
      { title: 'Maintainable', body: 'Routes → Controller → Service → Repository.' },
      { title: 'Documented', body: 'Schemas feed Swagger at /docs.' },
      { title: 'Scalable', body: 'Encapsulation keeps concerns local.' },
    ],
    stage: 'goals',
    camera: cam({ scale: 1, y: 20 }),
    corePower: 0.1,
    sound: 'pulse',
  },
  {
    id: 'a2-factory',
    act: 2,
    label: 'buildApp()',
    headline: 'The server is born in a factory.',
    body: 'buildApp() creates Fastify, registers infrastructure, then modules, then /health.',
    points: [
      { title: 'Logger', body: 'Pino via buildLoggerConfig().' },
      { title: 'AJV', body: 'removeAdditional · coerceTypes · allErrors.' },
      { title: 'Order', body: 'Plugins first — modules second.' },
    ],
    stage: 'boot',
    highlight: 0,
    snippet: SNIPPETS.buildApp,
    codeSide: 'right',
    camera: cam({ scale: 1.15, x: -40 }),
    corePower: 0.55,
    sound: 'boot',
  },
  {
    id: 'a2-listen',
    act: 2,
    label: 'Listen',
    headline: 'Then the process comes alive.',
    body: 'server.ts connects MongoDB, listens, and wires graceful shutdown.',
    points: [
      { title: 'Database', body: 'connectDatabase before listen.' },
      { title: 'Docs', body: 'Swagger at /docs.' },
      { title: 'Shutdown', body: 'app.close() then disconnectDatabase().' },
    ],
    stage: 'boot',
    highlight: 4,
    snippet: SNIPPETS.serverMain,
    codeSide: 'right',
    camera: cam({ scale: 1.2, x: -30 }),
    corePower: 1,
    sound: 'connect',
  },
  {
    id: 'a3-order',
    act: 3,
    label: 'Order',
    headline: 'Infrastructure docks in deliberate order.',
    body: 'Errors first. Security next. Auth helpers. Docs last. Rate limit is opt-in.',
    stage: 'plugins',
    highlight: -1,
    snippet: SNIPPETS.registerPlugins,
    codeSide: 'left',
    camera: cam({ scale: 1.1, y: -30 }),
    corePower: 1,
    sound: 'whoosh',
  },
  {
    id: 'a3-errors',
    act: 3,
    label: 'Errors',
    headline: 'Error Handler',
    body: 'One failure surface: AppError mapping + consistent 404.',
    stage: 'plugins',
    highlight: 0,
    snippet: SNIPPETS.registerPlugins,
    codeSide: 'left',
    camera: cam({ scale: 1.25, x: 60, y: -40 }),
    corePower: 1,
    sound: 'connect',
  },
  {
    id: 'a3-security',
    act: 3,
    label: 'Security',
    headline: 'CORS · Helmet · Rate Limit',
    body: 'Credentialed origins. Hardened headers. Auth capped at 10 req/IP/min.',
    stage: 'plugins',
    highlight: 2,
    snippet: SNIPPETS.registerPlugins,
    codeSide: 'left',
    camera: cam({ scale: 1.25, x: -20, y: -50 }),
    corePower: 1,
    sound: 'connect',
  },
  {
    id: 'a3-auth-plugins',
    act: 3,
    label: 'Identity',
    headline: 'Cookie + JWT',
    body: 'Signed with @fastify/jwt. Stored httpOnly — safe from XSS.',
    stage: 'plugins',
    highlight: 6,
    snippet: SNIPPETS.authCookie,
    codeSide: 'right',
    camera: cam({ scale: 1.3, x: -80 }),
    corePower: 1,
    sound: 'connect',
  },
  {
    id: 'a3-swagger',
    act: 3,
    label: 'Docs',
    headline: 'Swagger is not an afterthought.',
    body: 'Route JSON Schemas become living docs at /docs.',
    stage: 'plugins',
    highlight: 7,
    snippet: SNIPPETS.registerPlugins,
    codeSide: 'left',
    camera: cam({ scale: 1.2, x: 40, y: 40 }),
    corePower: 1,
    sound: 'pulse',
  },
  {
    id: 'a4-modules',
    act: 4,
    label: 'Modules',
    headline: 'Ten towers. One API prefix.',
    body: 'API_PREFIX = /api/v1. Each module is an independent Fastify plugin.',
    points: [
      { title: 'Isolation', body: 'Auth never imports Watchlist internals.' },
      { title: 'Shared kernel', body: 'common/ for errors & helpers.' },
      { title: 'Health', body: 'GET /health outside the prefix.' },
    ],
    stage: 'modules',
    highlight: -1,
    snippet: SNIPPETS.registerModules,
    codeSide: 'bottom',
    camera: cam({ scale: 1.05, y: 40 }),
    corePower: 1,
    sound: 'whoosh',
  },
  {
    id: 'a4-auth',
    act: 4,
    label: 'Auth',
    headline: 'Auth is the identity boundary.',
    body: 'Register, login, logout. Rate-limited. Cookie + token envelope.',
    stage: 'modules',
    highlight: 0,
    snippet: SNIPPETS.authRoutes,
    codeSide: 'right',
    camera: cam({ scale: 1.35, x: -100, y: 20 }),
    corePower: 1,
    sound: 'pulse',
  },
  {
    id: 'a5-layers',
    act: 5,
    label: 'Layers',
    headline: 'Dive the Auth shaft.',
    body: 'Routes → Controller → Service → Repository → MongoDB. Auth reuses UsersRepository.',
    stage: 'layers',
    highlight: 0,
    snippet: SNIPPETS.authRoutes,
    codeSide: 'right',
    camera: cam({ scale: 1.4, x: 80 }),
    corePower: 1,
    sound: 'whoosh',
  },
  {
    id: 'a5-controller',
    act: 5,
    label: 'Controller',
    headline: 'Controllers stay thin.',
    body: 'parseOrThrow · service · jwtSign · cookie · envelope.',
    stage: 'layers',
    highlight: 1,
    snippet: SNIPPETS.authController,
    codeSide: 'right',
    camera: cam({ scale: 1.45, x: 90, y: 30 }),
    corePower: 1,
    sound: 'connect',
  },
  {
    id: 'a5-service',
    act: 5,
    label: 'Service',
    headline: 'No Fastify types here.',
    body: 'AuthService + UsersRepository. bcrypt. ConflictError / UnauthorizedError.',
    stage: 'layers',
    highlight: 2,
    snippet: SNIPPETS.authService,
    codeSide: 'right',
    camera: cam({ scale: 1.5, x: 100, y: 60 }),
    corePower: 1,
    sound: 'connect',
  },
  {
    id: 'a5-repo',
    act: 5,
    label: 'Repository',
    headline: 'Persistence is delegated.',
    body: 'auth.repository is empty on purpose — Users owns the model.',
    stage: 'layers',
    highlight: 3,
    snippet: SNIPPETS.authRoutes,
    codeSide: 'right',
    camera: cam({ scale: 1.55, x: 110, y: 90 }),
    corePower: 1,
    sound: 'pulse',
  },
  {
    id: 'a6-start',
    act: 6,
    label: 'Request',
    headline: 'Follow the login request.',
    body: 'POST /api/v1/auth/login leaves the browser. Watch the hero travel.',
    stage: 'request',
    highlight: 0,
    snippet: SNIPPETS.authRoutes,
    codeSide: 'bottom',
    camera: cam({ scale: 1.1 }),
    corePower: 1,
    sound: 'whoosh',
  },
  {
    id: 'a6-plugins',
    act: 6,
    label: 'Plugins',
    headline: 'Cross-cutting first.',
    body: 'CORS · Helmet · Rate limit · Cookie — then the route.',
    stage: 'request',
    highlight: 2,
    snippet: SNIPPETS.registerPlugins,
    codeSide: 'bottom',
    camera: cam({ scale: 1.15, x: -20 }),
    corePower: 1,
    sound: 'connect',
  },
  {
    id: 'a6-handler',
    act: 6,
    label: 'Handler',
    headline: 'Route → Controller → Service → Repo',
    body: 'Zod validates. Credentials verified. Mongo answers.',
    stage: 'request',
    highlight: 5,
    snippet: SNIPPETS.authController,
    codeSide: 'bottom',
    camera: cam({ scale: 1.2, x: 40 }),
    corePower: 1,
    sound: 'connect',
  },
  {
    id: 'a6-response',
    act: 6,
    label: 'Reply',
    headline: 'The reply rides home.',
    body: 'jwtSign · httpOnly cookie · { success, data }.',
    stage: 'request',
    highlight: 7,
    snippet: SNIPPETS.authCookie,
    codeSide: 'bottom',
    camera: cam({ scale: 1.1, x: -40 }),
    corePower: 1,
    sound: 'pulse',
  },
  {
    id: 'a7-concepts',
    act: 7,
    label: 'Vocabulary',
    headline: 'Concepts where they live.',
    body: 'Architecture first — vocabulary snaps into place.',
    stage: 'concepts',
    highlight: 0,
    snippet: SNIPPETS.buildApp,
    codeSide: 'left',
    camera: cam({ scale: 1.1 }),
    corePower: 1,
    sound: 'whoosh',
  },
  {
    id: 'a7-register',
    act: 7,
    label: 'register()',
    headline: 'register() grows the world.',
    body: 'Plugins and modules use the same docking mechanism.',
    stage: 'concepts',
    highlight: 1,
    snippet: SNIPPETS.registerPlugins,
    codeSide: 'left',
    camera: cam({ scale: 1.15, y: -20 }),
    corePower: 1,
    sound: 'pulse',
  },
  {
    id: 'a7-schemas',
    act: 7,
    label: 'Schemas',
    headline: 'Schemas power validation and docs.',
    body: 'AJV on routes. Zod in controllers. Swagger from schemas.',
    stage: 'concepts',
    highlight: 5,
    snippet: SNIPPETS.authRoutes,
    codeSide: 'right',
    camera: cam({ scale: 1.2, x: 50 }),
    corePower: 1,
    sound: 'connect',
  },
  {
    id: 'a8-repos',
    act: 8,
    label: 'Patterns',
    headline: 'Not every repository speaks Mongo.',
    body: 'Same slot. Different ports: CRUD, HTTP, aggregation, composition.',
    stage: 'repos',
    highlight: -1,
    camera: cam({ scale: 1.05 }),
    corePower: 1,
    sound: 'whoosh',
  },
  {
    id: 'a8-tmdb',
    act: 8,
    label: 'TMDb',
    headline: 'External API repository.',
    body: 'TMDb wraps api.themoviedb.org — still a repository to services.',
    stage: 'repos',
    highlight: 1,
    camera: cam({ scale: 1.2, x: 60 }),
    corePower: 1,
    sound: 'pulse',
  },
  {
    id: 'a9-overview',
    act: 9,
    label: 'Overview',
    headline: 'The complete CineTrack backend.',
    body: 'Browser → Fastify → Plugins → Modules → Controllers → Services → Repos → MongoDB / TMDb.',
    points: [
      { title: 'Entry', body: 'server.ts + buildApp()' },
      { title: 'Shield', body: '8 infrastructure plugins' },
      { title: 'Domains', body: '10 modules under /api/v1' },
      { title: 'Contract', body: 'Schemas → AJV → Swagger' },
    ],
    stage: 'overview',
    snippet: SNIPPETS.buildApp,
    codeSide: 'bottom',
    camera: cam({ scale: 0.85, y: -20 }),
    corePower: 1,
    sound: 'whoosh',
  },
  {
    id: 'a10-compare',
    act: 10,
    label: 'Compare',
    headline: 'Why Fastify for CineTrack?',
    body: 'Express: middleware freedom. Fastify: plugins, schemas, Swagger that stays honest.',
    points: [
      { title: 'Express', body: 'Middleware · manual structure · docs bolted on.' },
      { title: 'Fastify', body: 'Plugins · encapsulation · AJV · Swagger · speed.' },
      { title: 'CineTrack', body: 'The architecture teaches by being real.' },
    ],
    stage: 'compare',
    camera: cam({ scale: 1 }),
    corePower: 1,
    sound: 'pulse',
  },
  {
    id: 'a10-end',
    act: 10,
    label: 'Close',
    headline: 'Architecture first. Code second.',
    body: 'You explored one real backend — from cold start to login — the structure that ships in CineTrack.',
    stage: 'overview',
    snippet: SNIPPETS.serverMain,
    codeSide: 'bottom',
    camera: cam({ scale: 0.9 }),
    corePower: 1,
    sound: 'pulse',
  },
];
