export interface CodeSnippet {
  file: string;
  title: string;
  lines: string[];
}

export const SNIPPETS = {
  buildApp: {
    file: 'server/src/app.ts',
    title: 'Application factory',
    lines: [
      'export async function buildApp() {',
      '  const app = Fastify({',
      '    logger: buildLoggerConfig(),',
      '    trustProxy: true,',
      '    ajv: { customOptions: {',
      '      removeAdditional: "all",',
      '      coerceTypes: true,',
      '      allErrors: true,',
      '    }},',
      '  });',
      '',
      '  await registerPlugins(app);',
      '  await registerModules(app);',
      '',
      '  app.get("/health", { schema: ... }, async () =>',
      '    success({ status: "ok", timestamp: new Date().toISOString() }),',
      '  );',
      '',
      '  return app;',
      '}',
    ],
  },
  serverMain: {
    file: 'server/src/server.ts',
    title: 'Process entry & graceful shutdown',
    lines: [
      'async function main(): Promise<void> {',
      '  app = await buildApp();',
      '  registerProcessHandlers();',
      '',
      '  await connectDatabase(app.log);',
      '  await app.listen({ port: env.PORT, host: env.HOST });',
      '',
      '  app.log.info(`CineTrack API listening on http://${env.HOST}:${env.PORT}`);',
      '  app.log.info(`Swagger docs available at .../docs`);',
      '}',
      '',
      'void main();',
    ],
  },
  registerPlugins: {
    file: 'server/src/plugins/index.ts',
    title: 'Infrastructure registration order',
    lines: [
      'export async function registerPlugins(app: FastifyInstance) {',
      '  await app.register(errorHandlerPlugin);',
      '  await app.register(corsPlugin);',
      '  await app.register(helmetPlugin);',
      '  await app.register(compressPlugin);',
      '  await app.register(rateLimitPlugin); // global: false',
      '  await app.register(cookiePlugin);',
      '  await app.register(jwtPlugin);',
      '  await app.register(swaggerPlugin);',
      '}',
    ],
  },
  registerModules: {
    file: 'server/src/modules/index.ts',
    title: 'Feature modules under /api/v1',
    lines: [
      'export async function registerModules(app: FastifyInstance) {',
      '  await app.register(authRoutes, { prefix: API_PREFIX });',
      '  await app.register(usersRoutes, { prefix: API_PREFIX });',
      '  await app.register(tmdbRoutes, { prefix: API_PREFIX });',
      '  await app.register(watchlistRoutes, { prefix: API_PREFIX });',
      '  await app.register(favoritesRoutes, { prefix: API_PREFIX });',
      '  await app.register(ratingsRoutes, { prefix: API_PREFIX });',
      '  await app.register(journalRoutes, { prefix: API_PREFIX });',
      '  await app.register(collectionsRoutes, { prefix: API_PREFIX });',
      '  await app.register(statisticsRoutes, { prefix: API_PREFIX });',
      '  await app.register(recommendationsRoutes, { prefix: API_PREFIX });',
      '}',
    ],
  },
  authRoutes: {
    file: 'server/src/modules/auth/auth.routes.ts',
    title: 'Auth routes + DI wiring',
    lines: [
      'const authRoutes: FastifyPluginAsync = async (fastify) => {',
      '  const service = createAuthService(usersRepository);',
      '  const controller = createAuthController(service);',
      '',
      '  fastify.post("/auth/login", {',
      '    config: { rateLimit: { max: 10, timeWindow: "1 minute" } },',
      '    schema: {',
      '      tags: ["Auth"],',
      '      summary: "Login with email and password",',
      '      body: { /* email, password */ },',
      '      response: { 200: authSuccessSchema },',
      '    },',
      '  }, async (request, reply) => controller.login(request, reply));',
      '};',
    ],
  },
  authController: {
    file: 'server/src/modules/auth/auth.controller.ts',
    title: 'Controller: validate → service → JWT cookie',
    lines: [
      'async login(request: FastifyRequest, reply: FastifyReply) {',
      '  const body = parseOrThrow(loginSchema, request.body);',
      '  const result = await this.service.login(body);',
      '',
      '  const accessToken = await reply.jwtSign({',
      '    sub: result.user.id,',
      '    email: result.user.email,',
      '  });',
      '',
      '  this.setAccessTokenCookie(reply, accessToken);',
      '',
      '  return success({ user: result.user, accessToken });',
      '}',
    ],
  },
  authService: {
    file: 'server/src/modules/auth/auth.service.ts',
    title: 'Service: business rules only',
    lines: [
      'async login(input: LoginInput): Promise<AuthResult> {',
      '  const user = await this.usersRepository',
      '    .findByEmailWithPassword(input.email);',
      '',
      '  if (!user) {',
      '    throw new UnauthorizedError("Invalid email or password");',
      '  }',
      '',
      '  const valid = await verifyPassword(input.password, user.passwordHash);',
      '  if (!valid) {',
      '    throw new UnauthorizedError("Invalid email or password");',
      '  }',
      '',
      '  return { user: { id: user.id, email: user.email, displayName: user.displayName } };',
      '}',
    ],
  },
  authCookie: {
    file: 'server/src/modules/auth/auth.controller.ts',
    title: 'httpOnly cookie transport',
    lines: [
      'private setAccessTokenCookie(reply: FastifyReply, accessToken: string) {',
      '  reply.setCookie(AuthConstants.ACCESS_TOKEN_COOKIE, accessToken, {',
      '    path: "/",',
      '    httpOnly: true,',
      '    sameSite: "lax",',
      '    secure: env.NODE_ENV === "production",',
      '  });',
      '}',
    ],
  },
  clientLogin: {
    file: 'client/src/app/core/services/auth.service.ts',
    title: 'Angular client → POST /api/v1/auth/login',
    lines: [
      "private readonly api = `${environment.apiUrl}/auth`; // /api/v1/auth",
      '',
      'login(payload: LoginPayload): Observable<AuthResponse> {',
      '  return this.http.post<AuthResponse>(`${this.api}/login`, payload).pipe(',
      '    tap((res) => this.handleAuthSuccess(res)),',
      '    catchError((err) => throwError(() => err)),',
      '  );',
      '}',
    ],
  },
  clientWatchlist: {
    file: 'client/src/app/core/services/watchlist.service.ts',
    title: 'Angular client → POST /api/v1/watchlist',
    lines: [
      'add(data: {',
      '  tmdbId: number;',
      '  mediaType: MediaType;',
      '  status?: WatchStatus;',
      '}): Observable<WatchlistItem> {',
      "  return this.api",
      "    .post<{ item: WatchlistItem }>('/watchlist', data)",
      '    .pipe(map((res) => res.data.item));',
      '}',
    ],
  },
  watchlistRoutes: {
    file: 'server/src/modules/watchlist/watchlist.routes.ts',
    title: 'Watchlist route + onRequest auth',
    lines: [
      'fastify.post(',
      "  '/watchlist',",
      '  {',
      '    onRequest: [authenticate],',
      '    schema: {',
      "      summary: 'Add a title to the watchlist',",
      '      body: { required: ["tmdbId", "mediaType"], ... },',
      '    },',
      '  },',
      '  async (request, reply) => controller.create(request, reply),',
      ');',
    ],
  },
  watchlistController: {
    file: 'server/src/modules/watchlist/watchlist.controller.ts',
    title: 'Watchlist controller create()',
    lines: [
      'async create(request: FastifyRequest, reply: FastifyReply) {',
      '  const auth = getAuthUser(request);',
      '  const body = parseOrThrow(createWatchlistItemSchema, request.body);',
      '  const item = await this.service.create(auth.sub, body);',
      '  return reply.status(HttpStatus.CREATED).send(success({ item }));',
      '}',
    ],
  },
  watchlistService: {
    file: 'server/src/modules/watchlist/watchlist.service.ts',
    title: 'Watchlist service create()',
    lines: [
      'async create(userId: string, input: CreateWatchlistItemInput) {',
      '  const existing = await this.repo.findByUserAndTitle(...);',
      '  if (existing) throw new ConflictError("Title is already on the watchlist");',
      '  return this.repo.create({ userId, ...input });',
      '}',
    ],
  },
  envLoad: {
    file: 'server/src/config/env.ts',
    title: 'Environment validation (Zod)',
    lines: [
      'loadDotenv();',
      '',
      'function loadEnv() {',
      '  const parsed = envSchema.safeParse(process.env);',
      '  if (!parsed.success) {',
      '    throw new Error(`Invalid environment configuration:\\n${prettifyError(parsed.error)}`);',
      '  }',
      '  return {',
      '    PORT: parsed.data.PORT,',
      '    HOST: parsed.data.HOST,',
      '    MONGODB_URI: parsed.data.MONGODB_URI,',
      '    JWT_SECRET: parsed.data.JWT_SECRET,',
      '    TMDB_API_KEY: parsed.data.TMDB_API_KEY,',
      '    CORS_ORIGIN: resolveCorsOrigin(parsed.data.CORS_ORIGIN),',
      '  } as const;',
      '}',
      '',
      'export const env = loadEnv(); // fails fast on import',
    ],
  },
  pluginError: {
    file: 'server/src/plugins/error-handler.ts',
    title: 'Global AppError + 404 surface',
    lines: [
      'fastify.setErrorHandler((error, request, reply) => {',
      '  if (isAppError(error)) {',
      '    return reply.status(error.statusCode)',
      '      .send(failure(error.message, error.code, error.statusCode, error.details));',
      '  }',
      '  if (error.validation) {',
      '    return reply.status(422).send(failure("Request validation failed", ...));',
      '  }',
      '  // 429 / 500 fallbacks...',
      '});',
      '',
      'fastify.setNotFoundHandler((request, reply) => {',
      '  return reply.status(404).send(failure("Route not found", ...));',
      '});',
    ],
  },
  pluginHelmet: {
    file: 'server/src/plugins/helmet.ts',
    title: 'Helmet — harden HTTP headers',
    lines: [
      'await fastify.register(helmet, {',
      '  // Relax CSP in development so Swagger UI assets load.',
      '  contentSecurityPolicy: env.isDevelopment ? false : undefined,',
      '  global: true,',
      '});',
    ],
  },
  pluginJwt: {
    file: 'server/src/plugins/jwt.ts',
    title: 'JWT — sign & cookie bridge',
    lines: [
      'await fastify.register(jwt, {',
      '  secret: env.JWT_SECRET,',
      '  sign: { expiresIn: env.JWT_EXPIRES_IN },',
      '  cookie: {',
      '    cookieName: AuthConstants.ACCESS_TOKEN_COOKIE,',
      '    signed: false,',
      '  },',
      '});',
    ],
  },
  pluginRateLimit: {
    file: 'server/src/plugins/rate-limit.ts',
    title: 'Rate limit — opt-in per route',
    lines: [
      'await fastify.register(rateLimit, {',
      '  global: false, // routes opt in via config.rateLimit',
      '  max: 100,',
      '  timeWindow: "1 minute",',
      '  addHeaders: {',
      '    "x-ratelimit-limit": true,',
      '    "x-ratelimit-remaining": true,',
      '    "retry-after": true,',
      '  },',
      '});',
    ],
  },
  pluginCors: {
    file: 'server/src/plugins/cors.ts',
    title: 'CORS — browser access',
    lines: [
      'await fastify.register(cors, {',
      '  origin: env.CORS_ORIGIN,',
      '  credentials: true,',
      '});',
    ],
  },
  responseHelpers: {
    file: 'server/src/common/utils/response.ts',
    title: 'Global success / failure envelopes',
    lines: [
      'export function success<T>(data: T, meta?: Record<string, unknown>) {',
      '  if (meta === undefined) return { success: true, data };',
      '  return { success: true, data, meta };',
      '}',
      '',
      'export function failure(',
      '  message: string, code: string, statusCode: number, details?: unknown,',
      ') {',
      '  return { success: false, error: { message, code, statusCode, details } };',
      '}',
    ],
  },
  appError: {
    file: 'server/src/common/errors/app-error.ts',
    title: 'Domain errors every service can throw',
    lines: [
      'export class AppError extends Error {',
      '  constructor(',
      '    message: string,',
      '    readonly statusCode: number,',
      '    readonly code: string,',
      '    readonly details?: unknown,',
      '  ) { super(message); }',
      '}',
      '',
      'export class UnauthorizedError extends AppError {',
      '  constructor(message = "Unauthorized") {',
      '    super(message, 401, "UNAUTHORIZED");',
      '  }',
      '}',
    ],
  },
  tmdbRepository: {
    file: 'server/src/modules/tmdb/tmdb.repository.ts',
    title: 'Server-side TMDb HTTP client',
    lines: [
      'private async request({ path, query }: TmdbRequestOptions) {',
      '  const url = new URL(`${env.TMDB_BASE_URL}${path}`);',
      "  url.searchParams.set('api_key', env.TMDB_API_KEY);",
      '',
      '  for (const [key, value] of Object.entries(query ?? {})) {',
      '    if (value !== undefined) url.searchParams.set(key, String(value));',
      '  }',
      '',
      "  const response = await fetch(url, { headers: { Accept: 'application/json' } });",
      '  if (!response.ok) {',
      '    throw new AppError("TMDb request failed", response.status === 404 ? 404 : 502);',
      '  }',
      '  return response.json();',
      '}',
    ],
  },
  clientTmdb: {
    file: 'client/src/app/core/services/tmdb.service.ts',
    title: 'Angular calls CineTrack — not TMDb directly',
    lines: [
      'search(query: string, page = 1): Observable<TmdbSearchResults> {',
      '  return this.api',
      "    .get<TmdbSearchResults>('/tmdb/search', { query, page })",
      '    .pipe(map((res) => res.data));',
      '}',
      '',
      "posterUrl(path: string | null, size = 'w342'): string {",
      "  if (!path) return 'assets/no-poster.svg';",
      '  return `${environment.tmdbImageBase}/${size}${path}`;',
      '}',
    ],
  },
  ngRoutes: {
    file: 'client/src/app/app.routes.ts',
    title: 'Lazy routes + guards',
    lines: [
      '{',
      "  path: 'login',",
      '  canActivate: [guestGuard],',
      '  loadComponent: () =>',
      "    import('./features/auth/login/login.component')",
      '      .then((m) => m.LoginComponent),',
      '},',
      '{',
      "  path: 'watchlist',",
      '  loadComponent: () =>',
      "    import('./features/watchlist/watchlist.component')",
      '      .then((m) => m.WatchlistComponent),',
      '},',
      '{',
      "  path: 'movie/:id',",
      '  loadComponent: () =>',
      "    import('./features/movie-details/movie-details.component')",
      '      .then((m) => m.MovieDetailsComponent),',
      '},',
    ],
  },
  ngAuthGuard: {
    file: 'client/src/app/core/guards/auth.guard.ts',
    title: 'authGuard — protect private pages',
    lines: [
      'export const authGuard: CanActivateFn = () => {',
      '  const auth = inject(AuthService);',
      '  const router = inject(Router);',
      '  if (auth.isAuthenticated()) return true;',
      "  return router.createUrlTree(['/login']);",
      '};',
      '',
      'export const guestGuard: CanActivateFn = () => {',
      '  const auth = inject(AuthService);',
      '  const router = inject(Router);',
      '  if (!auth.isAuthenticated()) return true;',
      "  return router.createUrlTree(['/dashboard']);",
      '};',
    ],
  },
  ngSignals: {
    file: 'client/src/app/core/services/auth.service.ts',
    title: 'Signals hold auth state',
    lines: [
      'private currentUser = signal<User | null>(null);',
      'private accessToken = signal<string | null>(null);',
      '',
      'readonly user = this.currentUser.asReadonly();',
      'readonly isAuthenticated = computed(() => !!this.currentUser());',
    ],
  },
  ngInterceptor: {
    file: 'client/src/app/core/interceptors/auth.interceptor.ts',
    title: 'Attach JWT on every HTTP call',
    lines: [
      'export const authInterceptor: HttpInterceptorFn = (req, next) => {',
      '  const auth = inject(AuthService);',
      '  const token = auth.getToken();',
      '  if (token) {',
      '    req = req.clone({',
      '      setHeaders: { Authorization: `Bearer ${token}` },',
      '    });',
      '  }',
      '  return next(req).pipe(',
      '    catchError((error: HttpErrorResponse) => {',
      '      if (error.status === 401) {',
      '        auth.logout();',
      "        inject(Router).navigate(['/login']);",
      '      }',
      '      return throwError(() => error);',
      '    }),',
      '  );',
      '};',
    ],
  },
  ngWatchlistLoad: {
    file: 'client/src/app/features/watchlist/watchlist.component.ts',
    title: 'Component + service + signals',
    lines: [
      'items = signal<WatchlistItem[]>([]);',
      'loading = signal(true);',
      '',
      'loadItems(): void {',
      '  this.loading.set(true);',
      '  this.watchlistService.getAll().subscribe({',
      '    next: (data) => {',
      '      this.items.set(data.items);',
      '      this.loading.set(false);',
      '    },',
      '    error: () => this.loading.set(false),',
      '  });',
      '}',
    ],
  },
  ngMovieCard: {
    file: 'client/src/app/shared/components/movie-card/movie-card.component.ts',
    title: 'Reusable MovieCard inputs',
    lines: [
      'export class MovieCardComponent {',
      '  media = input.required<TmdbMedia>();',
      '  showWatchedBadge = input(false);',
      '',
      '  detailRoute(): string {',
      '    const m = this.media();',
      "    const type = m.media_type || (m.title ? 'movie' : 'tv');",
      '    return `/${type}/${m.id}`;',
      '  }',
      '}',
    ],
  },
  ngWatchlistAdd: {
    file: 'client/src/app/features/movie-details/movie-details.component.ts',
    title: 'Add to watchlist from details',
    lines: [
      'addToWatchlist(status: WatchStatus | null): void {',
      '  const m = this.movie();',
      '  if (!m || !status) return;',
      '  this.watchlistService',
      '    .add({ tmdbId: m.id, mediaType: "movie", status })',
      '    .subscribe({',
      '      next: () => this.toast.success("Added to watchlist"),',
      '      error: (err) => this.toast.error(err.error?.error?.message || "Failed"),',
      '    });',
      '}',
    ],
  },
} as const satisfies Record<string, CodeSnippet>;
